---
- name: Capture server information
  hosts: all
  become: yes
  tasks:
    - name: Define output file path
      set_fact:
        output_file: "/u/spool/30/premigrationcheck/server_info_{{ inventory_hostname }}.txt"

    - name: Run commands and capture output
      command: "{{ item }}"
      register: command_output
      ignore_errors: yes
      with_items:
        - uptime
        - uname -a
        - df -PTH
        - cat /etc/fstab
        - adinfo
        - cat /etc/shadow
        - ifconfig
        - ifconfig -a
        - route -n
        - ip a
        - cat /etc/hosts
        - ls -la /dev/infmx
        - cat /etc/udev/rules.d/99-informix.rules
        - ls -la /dev/oracle
        - cat /etc/udev/rules.d/99-oracle.rules

    - name: Create output file
      copy:
        content: |
          {% for item in command_output.results %}
          Output for {{ item.item }}:
          {{ item.stdout | default('No output', true) }}
          {% endfor %}
        dest: "{{ output_file }}"
